# Generated by Django 5.1.2 on 2024-10-12 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('parliament_number', models.IntegerField()),
                ('session_number', models.IntegerField()),
                ('bill_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('introduced_date', models.DateField()),
                ('royal_assent_date', models.DateField(blank=True, null=True)),
                ('full_text_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
                ('appointed_date', models.DateField()),
                ('political_affiliation', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_yeas', models.IntegerField()),
                ('total_nays', models.IntegerField()),
                ('total_abstain', models.IntegerField()),
                ('vote_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='view_app.bill')),
            ],
        ),
    ]
